global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3001']
    metrics_path: '/metrics'

  - job_name: 'gto-service'
    static_configs:
      - targets: ['gto-service:8000']
    metrics_path: '/metrics'

  - job_name: 'opponent-service'
    static_configs:
      - targets: ['opponent-service:8000']
    metrics_path: '/metrics'

  - job_name: 'profile-service'
    static_configs:
      - targets: ['profile-service:8000']
    metrics_path: '/metrics'

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendation-service:8000']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
